newsletter/urls.py
from django.urls import path, register_converter

from .converters import NewsletterActionsConverter
from .views import (
    NewsletterListView, NewsletterDetailView,
    SubmissionArchiveIndexView, SubmissionArchiveDetailView,
    SubscribeRequestView, UnsubscribeRequestView, UpdateRequestView,
    ActionTemplateView, UpdateSubscriptionView,
)

register_converter(NewsletterActionsConverter, 'actions')

app_name = 'newsletter'
urlpatterns = [
    # Newsletter list and detail view
    path('', NewsletterListView.as_view(), name='list'),
    path(
        '<newsletter_slug>/',
        NewsletterDetailView.as_view(), name='detail'
    ),

    # Action request views
    path(
        '<newsletter_slug>/subscribe/',
        SubscribeRequestView.as_view(),
        name='subscribe_request'
    ),
    path(
        '<newsletter_slug>/subscribe/confirm/',
        SubscribeRequestView.as_view(confirm=True),
        name='subscribe_confirm'
    ),
    path(
        '<newsletter_slug>/update/',
        UpdateRequestView.as_view(),
        name='update_request'
    ),
    path(
        '<newsletter_slug>/unsubscribe/',
        UnsubscribeRequestView.as_view(),
        name='unsubscribe_request'
    ),
    path(
        '<newsletter_slug>/unsubscribe/confirm/',
        UnsubscribeRequestView.as_view(confirm=True),
        name='unsubscribe_confirm'
    ),

    # Activation email sent view
    path(
        '<newsletter_slug>/<actions:action>/email-sent/',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_email_sent.html'
        ),
        name='activation_email_sent'),

    # Action confirmation views
    path(
        '<newsletter_slug>/subscription/<email>/<actions:action>/activate/<activation_code>/',
        UpdateSubscriptionView.as_view(), name='update_activate'
    ),
    path(
        '<newsletter_slug>/subscription/<email>/<actions:action>/activate/',
        UpdateSubscriptionView.as_view(), name='update'
    ),

    # Action activation completed view
    path(
        '<newsletter_slug>/<actions:action>/activation-completed/',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_activated.html'
        ),
        name='action_activated'),

    # Archive views
    path(
        '<newsletter_slug>/archive/<year>/<month>/<day>/<slug>/',
        SubmissionArchiveDetailView.as_view(), name='archive_detail'
    ),
    path(
        '<newsletter_slug>/archive/',
        SubmissionArchiveIndexView.as_view(), name='archive'
    ),
]

newsletter/templates/newsletter/mailing_archive.html
{% extends "newsletter/common.html" %}
{% load i18n %}
{% block title %}{% trans "Newsletter archive" %}{% endblock title %}
{% block body %}
<table>
    <tr>
        <th>{% trans "Newsletter archive" %} {{ newsletter.title }}</th>
    </tr>
    {% for mailing in latest %}
    <tr>
        <td><a href="{{ mailing.get_absolute_url }}">{{ mailing }}</a></td>
    </tr>
    {% endfor %}
    <tr>
        <td><a href="../">Back to list</a></td>
    </tr>
</table>
{% endblock body %}

newsletter/templates/newsletter/newsletter_detail.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter detail" %}{% endblock title %}

{% block body %}
<table>
    <tr>
        <th>{% trans "Newsletter" %} {{ object.title }}</th>
    </tr>
    <tr>
        <td><a href="{% url 'newsletter:subscribe_request' object.slug %}">{% trans "Subscribe" %}</a></td>
    </tr>
    {% if not user.is_authenticated %}
    <tr>
        <td><a href="{% url 'newsletter:update_request' object.slug %}">{% trans "Update" %}</a></td>
    </tr>
    {% endif %}
    <tr>
        <td><a href="{% url 'newsletter:unsubscribe_request' object.slug %}">{% trans "Unsubscribe" %}</a></td>
    </tr>
    <tr>
        <td><a href="{% url 'newsletter:archive' object.slug %}">{% trans "Archive" %}</a></td>
    </tr>
    <tr>
        <td><a href="../">{% trans "Back to list" %}</a></td>
    </tr>
</table>
{% endblock body %}

newsletter/templates/newsletter/newsletter_list.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter list" %}{% endblock title %}

{% block body %}
{% if user.is_authenticated %}
<form method="POST" action="">
  {% csrf_token %}
  {{ formset.management_form }}
  <table>
    <tr>
        <th>{% trans "Newsletter" %}</th>
        {% if user %}
        <th>{% trans "Subscribe" %}</th>
        {% endif %}
    </tr>
    {% for form in formset.forms %}
      <tr>
        <td>{{ form.id }}{{ form.newsletter }}
<a href="{% url 'newsletter:detail' form.instance.newsletter.slug %}">{{ form.instance.newsletter.title }}</a></td>
        <td>{{ form.subscribed }}</td>
      </tr>
    {% endfor %}
  </table>
  <p><input id="id_submit" name="submit" value="{% trans "Update subscriptions" %}" type="submit" /></p>
</form>
{% else %}
<table>
    <tr>
        <th>{% trans "Newsletter" %}</th>
    </tr>
    {% for newsletter in object_list %}
    <tr>
        <td><a href="{% url 'newsletter:detail' newsletter.slug %}">{{ newsletter.title }}</a></td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock body %}

newsletter/templates/newsletter/submission_archive.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter archive" %}{% endblock title %}

{% block body %}
<table>
    <tr>
        <th>{% trans "Newsletter archive" %} {{ newsletter.title }}</th>
    </tr>
    {% for submission in latest %}
    <tr>
        <td><a href="{{ submission.get_absolute_url }}">{{ submission }}</a></td>
    </tr>
    {% endfor %}
    <tr>
        <td><a href="../">{% trans "Back to list" %}</a></td>
    </tr>
</table>
{% endblock body %}

newsletter/templates/newsletter/subscription_subscribe.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter subscribe" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter subscribe" %} {{ newsletter.title }}</h1>

    {% if error %}
        <p>{% trans "Due to a technical error we were not able to submit your confirmation email. This could be because your email address is invalid." %}</p>

        {% comment %} Replace the the following dummy with a valid email address and remove this comment.

        <p>{% trans "If the error persists, please don't hesitate to contact us at the following email address:" %} <a href="mailto:info@foobar.com">info@foobar.com</a></p>

        {% endcomment %}
    {% else %}
        <form enctype="multipart/form-data" method="post" action=".">
            {% csrf_token %}
            {{ form.as_p }}
            <p><input id="id_submit" name="submit" value="{% trans "Subscribe" %}" type="submit" /></p>
        </form>
    {% endif %}
{% endblock body %}

newsletter/templates/newsletter/subscription_subscribe_activated.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter" %} {{ newsletter.title }} {{ action }} {% trans "activate" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter" %} {{ newsletter.title }} {{ action }} {% trans "activate" %}</h1>

    <p>{% trans "Your subscription has successfully been activated." %}</p>
{% endblock body %}

newsletter/templates/newsletter/subscription_subscribe_email_sent.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter subscribe" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter subscribe" %} {{ newsletter.title }}</h1>

    <p>{% trans "Your subscription request was successfully received and an activation email has been sent to you. In that email you will find a link which you need to follow in order to activate your subscription." %}</p>
{% endblock body %}

newsletter/templates/newsletter/subscription_subscribe_user.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter subscribe" %}{% endblock title %}

{% block body %}
<h1>{% trans "Newsletter subscribe" %} {{ newsletter.title }}</h1>

<p>Welcome, {{ user }}!</p>

{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% else %}
{% trans "Do you want to subscribe to this newsletter?" %}
<form enctype="multipart/form-data" method="post" action="{% url 'newsletter:subscribe_confirm' newsletter.slug %}">
    {% csrf_token %}
    <p><input id="id_submit" name="submit" value="{% trans "Subscribe" %}" type="submit" /></p>
</form>
{% endif %}
{% endblock body %}

newsletter/templates/newsletter/subscription_unsubscribe_activated.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter" %} {{ newsletter.title }} {{ action }} {% trans "activate" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter" %} {{ newsletter.title }} {{ action }} {% trans "activate" %}</h1>

    <p>{% trans "You have successfully been unsubscribed." %}</p>
{% endblock body %}

newsletter/templates/newsletter/subscription_unsubscribe_email_sent.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter unsubscribe" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter unsubscribe" %} {{ newsletter.title }}</h1>

    <p>{% trans "Your unsubscription request has successfully been received. An email has been sent to you with a link you need to follow in order to confirm your unsubscription." %}</p>
{% endblock body %}

newsletter/templates/newsletter/subscription_unsubscribe_user.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter unsubscribe" %}{% endblock title %}

{% block body %}
<h1>{% trans "Newsletter unsubscribe" %} {{ newsletter.title }}</h1>

<p>Welcome, {{ user }}!</p>

{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% else %}

{% trans "Do you want to unsubscribe from this newsletter?" %}
<form enctype="multipart/form-data" method="post" action="{% url 'newsletter:unsubscribe_confirm' newsletter.slug %}">
    {% csrf_token %}
    <p><input id="id_submit" name="submit" value="{% trans "Unsubscribe" %}" type="submit" /></p>
</form>
{% endif %}

{% endblock body %}

newsletter/templates/newsletter/subscription_update.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter update" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter update" %} {{ newsletter.title }}</h1>

    {% if error %}
        <p>{% trans "Due to a technical error we were not able to submit your confirmation email. This could be because your email address is invalid." %}</p>

        {% comment %} Replace the the following dummy with a valid email address and remove this comment.

        <p>{% trans "If the error persists, please don't hesitate to contact us at the following email address:" %} <a href="mailto:info@foobar.com">info@foobar.com</a></p>

        {% endcomment %}
    {% else %}
        <form enctype="multipart/form-data" method="post" action=".">
            {% csrf_token %}
            {{ form.as_p }}
            <p><input id="id_submit" name="submit" value="{% trans "Update subscription" %}" type="submit" /></p>
        </form>
    {% endif %}
{% endblock body %}

newsletter/templates/newsletter/subscription_update_activated.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter" %} {{ newsletter.title }} {{ action }} {% trans "activate" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter" %} {{ newsletter.title }} {{ action }} {% trans "activate" %}</h1>

    <p>{% trans "Your subscription has successfully been updated." %}</p>
{% endblock body %}

newsletter/templates/newsletter/subscription_update_email_sent.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter update" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter update" %} {{ newsletter.title }}</h1>

    <p>{% trans "Your update request was successfully received and an activation email has been sent to you. In that email you will find a link which you need to follow in order to update your subscription." %}</p>
{% endblock body %}